### ISSUE TITLE
Make the Tryon easily integratable

### ISSUE THREAD

**Issue by post2seth** [ninesystems/Virtual-tryon#2]
Make the tryon easily integratable like any jquery plugin, so anyone can integrate that with their system.

**Comment by najib236** [comment]
Hi sir :)
do you have any documentation about how to run Tryon ?

Thank you so much.

**Comment by post2seth** [comment]
Hello Njib,

For how to run, i mentioned at readme. But still if you didn't find, then
you can run by following these steps

1. Checkout from git
2. Run build.bat file
3. There will be a newly created Build folder
4. Open that Build folder
5. Open index.html page in browser


I am also creating a document how to make glasses for tryon and how to add
those to tryon.

**Comment by ninesys** [comment]
Done. will release a guide for that soon.
