### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by dencocimbom** [ninesystems/Virtual-tryon#6]
I ran build.bat. After that I opened Build folder and run index page. But it doesn't work. See pictures
![greska1](https://user-images.githubusercontent.com/63068326/79082828-06899600-7d2a-11ea-9b88-685bdcb2632d.png)
![greska2](https://user-images.githubusercontent.com/63068326/79082829-07bac300-7d2a-11ea-8e04-ce3718c7cebc.png)

**Comment by ninesys** [comment]
you need to have java in your system. try installing java & after that check in cmd prompt by running java -v
if that run successfully then it will compile the code.

**Comment by ninesys** [comment]
Try the newer version now, its working with npm environment only
